package com.inventory.inventory_system.util;

import com.inventory.inventory_system.dto.ProductDTO;
import com.inventory.inventory_system.entity.Product;

import java.util.List;
import java.util.stream.Collectors;

public class DTOMapper {

    // Convert Product entity to ProductDTO
    public static ProductDTO toProductDTO(Product product) {
        if (product == null) return null;
        
        ProductDTO dto = new ProductDTO();
        dto.setId(product.getId());
        dto.setName(product.getName());
        dto.setCategory(product.getCategory());
        dto.setPrice(product.getPrice());
        dto.setQuantity(product.getQuantity());
        
        // Handle null reorderLevel safely - this is critical for avoiding NPE
        Integer reorderLevel = product.getReorderLevel();
        if (reorderLevel == null) {
            System.err.println("WARNING: Product " + product.getId() + " (" + product.getName() + ") has null reorderLevel. Setting to 0.");
            reorderLevel = 0;
        }
        dto.setReorderLevel(reorderLevel);
        
        // Calculate derived fields with null-safe reorderLevel
        dto.setTotalValue(product.getPrice() * product.getQuantity());
        dto.setStockStatus(determineStockStatus(product.getQuantity(), reorderLevel));
        
        return dto;
    }

    // Convert ProductDTO to Product entity
    public static Product toProduct(ProductDTO dto) {
        if (dto == null) return null;
        
        Product product = new Product();
        // Don't set ID - it's auto-generated by JPA
        product.setName(dto.getName());
        product.setCategory(dto.getCategory());
        product.setPrice(dto.getPrice() != null ? dto.getPrice() : 0.0);
        product.setQuantity(dto.getQuantity() != null ? dto.getQuantity() : 0);
        product.setReorderLevel(dto.getReorderLevel() != null ? dto.getReorderLevel() : 0);
        
        return product;
    }

    // Convert list of Product entities to ProductDTOs
    public static List<ProductDTO> toProductDTOList(List<Product> products) {
        return products.stream()
                .map(DTOMapper::toProductDTO)
                .collect(Collectors.toList());
    }

    // Convert list of ProductDTOs to Product entities
    public static List<Product> toProductList(List<ProductDTO> dtos) {
        return dtos.stream()
                .map(DTOMapper::toProduct)
                .collect(Collectors.toList());
    }

    // Helper method to determine stock status
    private static String determineStockStatus(int quantity, int reorderLevel) {
        if (quantity == 0) return "OUT_OF_STOCK";
        if (quantity <= reorderLevel) return "LOW_STOCK";
        return "IN_STOCK";
    }

    // Update existing Product entity with ProductDTO data
    public static void updateProductFromDTO(Product product, ProductDTO dto) {
        if (product == null || dto == null) return;
        
        product.setName(dto.getName());
        product.setCategory(dto.getCategory());
        product.setPrice(dto.getPrice());
        product.setQuantity(dto.getQuantity());
        product.setReorderLevel(dto.getReorderLevel());
    }
}